server:
  port: 8090
spring:
  data:
    mongodb:
      username: vendetta
      password: vendetta
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin