server:
  port: 8040
spring:
  data:
    mongodb:
      username: vendetta
      password: vendetta
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-severs: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.spring.framework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.package: '*'
        spring.json.type.mapping: orderConfirmation:com.vendetta.ecommerce.kafka.OrderConfirmation, orderConfirmation:com.vendetta.ecommerce.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: vendetta
    password: vendetta
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000